export const daftarPelajaranSenin = [
    {
        subjectId: 'upacara',
        nama: 'Upacara Bendera',
        jadwal: '07:15 - 08:00',
    },
    {
        subjectId: 'mtk-minat',
        nama: 'Matematika Peminatan',
        jadwal: '08:00 - 08:40',
        guru: 'Gilang',
        color: '#ec4899',
    },
    {
        subjectId: 'mtk-minat',
        nama: 'Matematika Peminatan',
        jadwal: '08:40 - 09:20',
        guru: 'Gilang',
        color: '#ec4899',
    },
    {
        subjectId: 'bindo',
        nama: 'Bahasa Indonesia',
        jadwal: '09:20 - 10:00',
        guru: 'Nani Septiani',
        color: '#eab308',
    },
    {
        subjectId: 'istirahat',
        nama: 'Istirahat',
        jadwal: '10:00 - 10:30',
    },
    {
        subjectId: 'bindo',
        nama: 'Bahasa Indonesia',
        jadwal: '10:30 - 11:15',
        guru: 'Nani Septiani',
        color: '#eab308',
    },
    {
        subjectId: 'senbud',
        nama: 'Seni Budaya',
        jadwal: '11:15 - 12:00',
        guru: 'Listra Yonathan',
        color: '#3b82f6',
    },
    {
        subjectId: 'ibadah-dan-istirahat',
        nama: 'Ibadah dan Istirahat',
        jadwal: '12:00 - 13:00',
    },
    {
        subjectId: 'senbud',
        nama: 'Seni Budaya',
        jadwal: '13:00 - 13:40',
        guru: 'Listra Yonathan',
        color: '#3b82f6',
    },
    {
        subjectId: 'sejindo',
        nama: 'Sejarah Indonesia',
        jadwal: '13:40 - 14:20',
        guru: 'Sutrisno',
        color: '#22c55e',
    },
    {
        subjectId: 'sejindo',
        nama: 'Sejarah Indonesia',
        jadwal: '14:20 - 15:00',
        guru: 'Sutrisno',
        color: '#22c55e',
    },
];
