#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling and checking your project before committing'

npm run format-all

# Check ESLint Standards
npm run check-lint ||
(
    echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
            ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'